# Define stages for the pipeline
stages:
  - install
  - build
  - deploy

# Stage 1: Install dependencies for React and Node.js
install_dependencies:
  stage: install
  image: node:16-alpine    # Using node image to install dependencies
  script:
    - echo "Installing dependencies..."
    - cd npm install   # Install React dependencies
    - ls -1
  cache:
    paths:
      - node_modules/


# Define a cache policy to reduce installation time
cache:
  paths:
    - node_modules/
