# Define stages for the pipeline
stages:
  - install
  - build
  - deploy


# Stage 1: Install dependencies for React and Node.js
install_dependencies:
  stage: install
  image: node    # Using node image to install dependencies
  script:
    - node -v
    - echo "Installing dependencies..."
    - npm install   # Install React dependencies

  cache:
    paths:
      - node_modules/

# # Stage 2: Build the React app (client)
build_react_app:
  stage: build
  image: node
  script:
    - echo "Building React app..."
    # - unset CI     # Unset CI to prevent treating warnings as errors
    - CI=false npm run build  # Build React app
  artifacts:
    paths:
      - build   # Save the React build folder as an artifact


# Stage 3: Deploy to AWS EC2
deploy_to_aws:
  stage: deploy
  image: node
  script:
    - echo "Deploying to AWS EC2..."
    - mkdir -p .ssh
    - echo "$EC2_SSH_PEM_KEY" | tr -d '\r' > ec2_key.pem
    - chmod 400 ec2_key.pem
    - mv ec2_key.pem .ssh
    - ssh-keyscan -H 54.153.198.123 >> ~/.ssh.know_hosts
    - scp -i .ssh/ec2_key.pem -r build ubuntu@54.153.198.123:/home/ubuntu


# Define a cache policy to reduce installation time
cache:
  paths:
    - node_modules/

