# Define stages for the pipeline
stages:
  - install
  - build

# Stage 1: Install dependencies for React and Node.js
install_dependencies:
  stage: install
  image: node    # Using node image to install dependencies
  script:
    - node -v
    - echo "Installing dependencies..."
    #- cd npm install   # Install React dependencies    
    - npm i

  cache:
    paths:
      - node_modules/

# Stage 2: Build the React app (client)
build_react_app:
  stage: build
  image: node
  script:
    - echo "Building React app..."
    # - unset CI     # Unset CI to prevent treating warnings as errors
    - CI=false npm run build  # Build React app
  artifacts:
    paths:
      - /build   # Save the React build folder as an artifact

# Define a cache policy to reduce installation time
cache:
  paths:
    - node_modules/

